name:               luna-manager
version:            "0.1"
author:             New Byte Order <contact@newbyteorder.com>
maintainer:         New Byte Order <contact@newbyteorder.com>

dependencies:
  - prologue
  - ansi-terminal
  - ascii-progress
  - io-streams
  - path
  - network
  - conduit
  - base
  - directory
  - exceptions
  - aeson
  - yaml
  - text
  - typed-process
  - http-conduit
  - http-types
  - filepath
  - network-uri
  - bytestring
  - optparse-applicative
  - split
  - lens
  - dependent-state
  - containers
  - resourcet
  - optparse-applicative
  - typelevel

  - lens-utils
  - constraints
  - transformers
  - mtl
  - shelly


default-extensions:
    - AllowAmbiguousTypes
    - ApplicativeDo
    - Arrows
    - BangPatterns
    - BinaryLiterals
    - ConstraintKinds
    - DataKinds
    - DefaultSignatures
    - DeriveDataTypeable
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - DoAndIfThenElse
    - DuplicateRecordFields
    - EmptyDataDecls
    - FlexibleContexts
    - FlexibleInstances
    - FunctionalDependencies
    - GeneralizedNewtypeDeriving
    - InstanceSigs
    - LambdaCase
    - MonadComprehensions
    - MultiWayIf
    - NamedWildCards
    - NegativeLiterals
    - NoImplicitPrelude
    - NumDecimals
    - OverloadedLabels
    - OverloadedStrings
    - PackageImports
    - QuasiQuotes
    - RankNTypes
    - RecursiveDo
    - ScopedTypeVariables
    - StandaloneDeriving
    - TemplateHaskell
    - TupleSections
    - TypeApplications
    - TypeFamilies
    - TypeFamilyDependencies
    - TypeOperators
    - ViewPatterns

    - LiberalTypeSynonyms
    - RelaxedPolyRec

executables:
  luna-manager:
    main:          Main.hs
    source-dirs:   src
    other-modules: Paths_luna_manager
