---
- hosts: all
  vars:
    http_port: 80
    max_clients: 200
  remote_user: vagrant
  become_user: root
  vars:
    home: '{{ ansible_env.HOME }}'
    luna_repo_path: 'ssh://git@github.com/luna/luna-manager'
    luna_dir: '{{ home }}/luna-develop'
    luna_tools_dir: '{{ luna_dir }}/tools'
    luna_apps_dir: '{{ luna_dir }}/apps'
    luna_libs_dir: '{{ luna_dir }}/libs'
    luna_manager_dir: '{{ luna_apps_dir }}/luna-manager'
    luna_studio_dir: '{{ luna_apps_dir }}/luna-studio'
    luna_manager_url: 'http://packages.luna-lang.org/linux/manager/luna-manager'
    pyenv_root: '{{ luna_tools_dir }}/python/pyenv'
    pyenv_bin: '{{ pyenv_root }}/bin/pyenv'
  environment:
    LD_LIBRARY_PATH: '{{ luna_libs_dir }}:{{ ansible_env.LD_LIBRARY_PATH | default("") }}'
    PYENV_ROOT: '{{ pyenv_root }}'


  tasks:
  - name: create the next luna studio version
    shell: 'source {{ luna_studio_dir }}/luna-shell.sh && luna-manager next-version {{ luna_studio_dir }}/luna-package.yaml'
    args:
      executable: /bin/bash
      chdir: '{{ luna_manager_dir }}'

  - name: build luna luna package
    shell: 'source {{ luna_studio_dir }}/luna-shell.sh && python deploy/build_package.py -p {{ luna_studio_dir }}'
    args:
      executable: /bin/bash
      chdir: '{{ luna_manager_dir }}'
